name: Deploy README

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Code
        uses: actions/checkout@v3
      - 
        name: Checkout Backend Code
        uses: actions/checkout@v3
        with:
          repository: 'BenHall-1/README-Backend'
          token: '${{ secrets.BACKEND_TOKEN }}'
          path: 'backend'
      - 
        name: Process README & Commit Changes
        run: |
          cp backend/outputs/output.md README.md
          rm -rf backend/
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Automatically Updated README.md"
          git push origin HEAD:main
         
